require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Octopus' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'

  pod 'RNUxcam', :path => '../node_modules/react-native-ux-cam'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'RNFBAnalytics', :path => '../node_modules/@react-native-firebase/analytics'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'OctopusTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Octopus-tvOS' do
  # Pods for Octopus-tvOS

  target 'Octopus-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
